env:
  browser: true
  es2021: true
extends: [
  "eslint:recommended",
  "plugin:@typescript-eslint/recommended",
  "plugin:@typescript-eslint/recommended-requiring-type-checking",
  "prettier"
]
overrides: [ ]
plugins: [ "@typescript-eslint" ]
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
rules: { }
