name: Build
description: Build the project

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      shell: bash
      run: yarn

    - name: Build
      shell: bash
      run: yarn build
