name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Bun
        uses: xhyrom/setup-bun@v0.1.7
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: ESLint
        run: bun lint
      - name: Prettier
        run: bun format
      #      - name: Jest
      #        run: npm run test
      - name: Typecheck
        run: bun typecheck
      - name: Build
        run: bun build
